name = "grpc"
main = "scr/grpc-worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[vars]
OBFUSCATION_KEY = "nautica-secure-key-2024"
ENVIRONMENT = "production"

[env.development]
name = "nautica-grpc-dev"
vars = { ENVIRONMENT = "development", DEBUG = "true" }

[env.staging]
name = "nautica-grpc-staging"
vars = { ENVIRONMENT = "staging" }

[env.production]
name = "nautica-grpc-prod"
vars = { ENVIRONMENT = "production" }

# KV Namespaces
[[kv_namespaces]]
binding = "PROXY_CONFIG"
id = "PROXY_CONFIG"
preview_id = "faadf2de2a6e4416a1da36f5f78cf2c3"

# Secrets
[secrets]
PRX_BANK_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Nautica/refs/heads/main/proxyList.txt"
REVERSE_PRX_TARGET = "ovo.id"
